version: "3"
services:
  app:
    image: node:18.16
    ports:
      - 3000:3000
    command: sh -c "cd /app && yarn && yarn build && yarn start"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
